[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"

[functions]
  node_bundler = "esbuild"
  node_version = "18"
  # Harden function bundling to avoid pulling unintended transitive versions
  external_node_modules = []
  included_files = []

[[plugins]]
  package = "@netlify/plugin-nextjs"
